/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c2d77fadcfd8806841a8e59782401022)
interface __BaseEnv_Env {
	DB: D1Database;
	Sandbox: DurableObjectNamespace<import("./worker/index").RepairSandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "RepairSandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
